
import java.awt.Canvas;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.image.ColorModel;
import java.awt.image.ConvolveOp;
import java.awt.image.Kernel;
import java.awt.image.MemoryImageSource;
import java.awt.image.PixelGrabber;
import java.awt.image.WritableRaster;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.StringReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * index.java
 *
 * Created on 17/Abr/2011, 15:03:17
 */
/**
 *
 * @author Goncalo
 */
public class index extends javax.swing.JFrame {

    private File Fileimg;
    private double[] array_3x3;
    private BufferedImage imagemOriginal;
    private BufferedImage imagemPanel;
    private double[][] mask;
    private float[] k_mask;

    /** Creates new form index */
    public index() {
        initComponents();
    }

    private void getMatrix() {
    }

    private BufferedImage callSobel(BufferedImage img) {
        BufferedImage edges = null;
        try {
            //create the detector
            SobelEdgeDetector detector = new SobelEdgeDetector();
            detector.setArray3x3(k_mask);
            //apply it to an image
            detector.setSourceImage(img);
            detector.process();
            edges = detector.getedgesImage();
            imagemPanel = edges;
            ImageIO.write(edges, "PNG", new File("SobelEdge.png"));
        } catch (Exception ex) {
            Logger.getLogger(index.class.getName()).log(Level.SEVERE, null, ex);
        }
        return edges;
    }

    private BufferedImage callCanny(BufferedImage img) {
        BufferedImage edges = null;
        try {
            //create the detector
            CannyEdgeDetector detector = new CannyEdgeDetector();
            //adjust its parameters as desired
            detector.setLowThreshold(0.5f);
            detector.setHighThreshold(1f);
            //apply it to an image
            detector.setSourceImage(img);
            detector.process();
            edges = detector.getEdgesImage();
            imagemPanel = edges;
            ImageIO.write(edges, "PNG", new File("CannyEdge.png"));
        } catch (Exception ex) {
            Logger.getLogger(index.class.getName()).log(Level.SEVERE, null, ex);
        }
        return edges;
    }

    private BufferedImage callRoberts(BufferedImage img) {
        BufferedImage edges = null;
        try {
            //create the detector
            RobertsEdgeDectector detector = new RobertsEdgeDectector();
            //apply it to an image
            detector.setSourceImage(img);
            detector.process();
            edges = detector.getedgesImage();
            imagemPanel = edges;
            ImageIO.write(edges, "PNG", new File("RobertsEdge.png"));
        } catch (Exception ex) {
            Logger.getLogger(index.class.getName()).log(Level.SEVERE, null, ex);
        }
        return edges;
    }

    private BufferedImage callPrewitt(BufferedImage img) {
        BufferedImage edges = null;
        try {
            //create the detector
            PrewittEdgeDectection detector = new PrewittEdgeDectection();
            //apply it to an image
            detector.setSourceImage(img);
            detector.process();
            edges = detector.getedgesImage();
            imagemPanel = edges;
            ImageIO.write(edges, "PNG", new File("PrewittEdge.png"));
        } catch (Exception ex) {
            Logger.getLogger(index.class.getName()).log(Level.SEVERE, null, ex);
        }
        return edges;
    }

    private void insertImage(BufferedImage img, JPanel jpanel) {
        try {
            Graphics g = jpanel.getGraphics();
            g.setColor(jpanel.getBackground());
            g.fillRect(0, 0, jpanel.getWidth(), jpanel.getWidth());
            if ((img.getWidth() > jpanel.getWidth()) || (img.getHeight() > jpanel.getHeight())) {
                g.drawImage(img, 0, 0, jpanel.getWidth(), jpanel.getHeight(), jpanel);
            } else {
                g.drawImage(img, 0, 0, jpanel);
            }
        } catch (Exception ex) {
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pImagem = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btCanny = new javax.swing.JButton();
        btLoadImg = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btSaveImg = new javax.swing.JButton();
        btSobel = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btCombine = new javax.swing.JButton();
        btRoberts = new javax.swing.JButton();
        btPrewitt = new javax.swing.JButton();
        cbOptions = new javax.swing.JComboBox();
        cbGrey = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMask = new javax.swing.JTextArea();
        btReadMask = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pImagem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pImagemMouseClicked(evt);
            }
        });
        pImagem.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));

        btCanny.setText("Canny");
        btCanny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCannyActionPerformed(evt);
            }
        });

        btLoadImg.setText("Open Image");
        btLoadImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoadImgActionPerformed(evt);
            }
        });

        btSaveImg.setText("Save Image");
        btSaveImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveImgActionPerformed(evt);
            }
        });

        btSobel.setText("Sobel");
        btSobel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSobelActionPerformed(evt);
            }
        });

        btCombine.setText("not working");
        btCombine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCombineActionPerformed(evt);
            }
        });

        btRoberts.setText("Roberts");
        btRoberts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRobertsActionPerformed(evt);
            }
        });

        btPrewitt.setText("Prewitt");
        btPrewitt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrewittActionPerformed(evt);
            }
        });

        cbOptions.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Default", "Smoothing", "Sharpening", "Raised", "Motion-blur", "Edge Detection" }));
        cbOptions.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbOptionsItemStateChanged(evt);
            }
        });

        cbGrey.setText("Colored?");

        txtMask.setColumns(12);
        txtMask.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtMask.setLineWrap(true);
        txtMask.setRows(1);
        txtMask.setText("-1 -1 -1\n0 0 0\n1 1 1\n");
        jScrollPane1.setViewportView(txtMask);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(btLoadImg, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(btSaveImg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(btCanny, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(btSobel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(btRoberts, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(btPrewitt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(btCombine, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbGrey, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbOptions, javax.swing.GroupLayout.Alignment.LEADING, 0, 106, Short.MAX_VALUE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btLoadImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSaveImg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCanny)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSobel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRoberts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPrewitt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCombine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbGrey)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btReadMask.setText("read Mask");
        btReadMask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReadMaskActionPerformed(evt);
            }
        });

        jButton1.setText("apply mask");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("re-apply mask");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btReadMask, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btReadMask)
                        .addGap(36, 36, 36)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void btCannyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCannyActionPerformed
        readMask();
        insertImage(callCanny(deepCopy(imagemOriginal)), pImagem);
    }//GEN-LAST:event_btCannyActionPerformed

    private void btLoadImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoadImgActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images", "jpg", "gif", "png");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                Fileimg = chooser.getSelectedFile();
                imagemOriginal = ImageIO.read(chooser.getSelectedFile());
            } catch (Exception ex) {
            }
            insertImage(imagemOriginal, pImagem);
        }
    }//GEN-LAST:event_btLoadImgActionPerformed

    public BufferedImage deepCopy(BufferedImage bi) {
        ColorModel cm = bi.getColorModel();
        boolean isAlphaPremultiplied = cm.isAlphaPremultiplied();
        WritableRaster raster = bi.copyData(null);
        return new BufferedImage(cm, raster, isAlphaPremultiplied, null);
    }
    private void btSaveImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveImgActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images", "jpg", "gif", "png");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                ImageIO.write(imagemPanel, "PNG", chooser.getSelectedFile());
            } catch (Exception ex) {
            }
        }
    }//GEN-LAST:event_btSaveImgActionPerformed

    private void btSobelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSobelActionPerformed
        readMask();
        insertImage(callSobel(deepCopy(imagemOriginal)), pImagem);
    }//GEN-LAST:event_btSobelActionPerformed

    private void btCombineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCombineActionPerformed
        try {
//            // load source images
//            BufferedImage overlay = ImageIO.read(new File("SobelEdge.png"));
//            // create the new image, canvas size is the max. of both image sizes
//            int w = Math.max(image.getWidth(), overlay.getWidth());
//            int h = Math.max(image.getHeight(), overlay.getHeight());
//            BufferedImage combined = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
//            // paint both images, preserving the alpha channels
//            Graphics g = combined.getGraphics();
//            g.drawImage(image, 0, 0, null);
//            g.drawImage(overlay, 0, 0, null);
//            // Save as new image
//            ImageIO.write(combined, "PNG", new File("combined.png"));



            BufferedImage image = ImageIO.read(new File("CannyEdge.png"));
            int[] ori = new int[image.getWidth() * image.getHeight()];
            PixelGrabber pg = new PixelGrabber(image, 0, 0, image.getWidth(), image.getHeight(), ori, 0, image.getWidth());
            try {
                pg.grabPixels();
            } catch (Exception e) {
                System.out.println("PixelGrabber failed");
            }
            BufferedImage image2 = ImageIO.read(new File("SobelEdge.png"));
            int[] ori2 = new int[image2.getWidth() * image2.getHeight()];
            PixelGrabber pg2 = new PixelGrabber(image2, 0, 0, image2.getWidth(), image2.getHeight(), ori2, 0, image2.getWidth());
            try {
                pg2.grabPixels();
            } catch (Exception e) {
                System.out.println("PixelGrabber failed");
            }


            int w = Math.max(image.getWidth(), image2.getWidth());
            int h = Math.max(image.getHeight(), image2.getHeight());

            int[] pixels = new int[w * h];
            for (int j = 0; j < pixels.length; j++) {
                if ((ori[j] & 0x00FFFFFF) != 0) {  //nao é preto, é branco
                    pixels[j] = ori[j];
                } else if ((ori2[j] & 0x00FFFFFF) != 0) { //nao é preto, é branco
                    pixels[j] = ori2[j];
                }
            }
            MemoryImageSource newImage = new MemoryImageSource(w, h, pixels, 0, w);
            Canvas c = new Canvas();
            Image finalImage = c.createImage(newImage);
            //BufferedImage combine = combine.createGraphics();
            imagemPanel.getGraphics().drawImage(finalImage, 0, 0, null);
            insertImage(imagemPanel, pImagem);


            ImageIO.write(imagemPanel, "PNG", new File("combined.png"));
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_btCombineActionPerformed

    private void btRobertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRobertsActionPerformed
        readMask();
        insertImage(callRoberts(deepCopy(imagemOriginal)), pImagem);
    }//GEN-LAST:event_btRobertsActionPerformed

    private void btPrewittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrewittActionPerformed
        readMask();
        insertImage(callPrewitt(deepCopy(imagemOriginal)), pImagem);
    }//GEN-LAST:event_btPrewittActionPerformed

    private void btReadMaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReadMaskActionPerformed
        String txt = txtMask.getText();
        String[] line = txt.split("\n");
        int lines = line.length;
        mask = new double[lines][];

        for (int y = 0; y < lines; y++) {
            String[] elem = line[y].split(" ");
            mask[y] = new double[elem.length];
            for (int x = 0; x < elem.length; x++) {
                mask[y][x] = Double.parseDouble(elem[x]);
            }
        }
        for (int y = 0; y < mask.length; y++) {
            System.out.println("");
            for (int x = 0; x < mask[y].length; x++) {
                System.out.print(mask[y][x] + "\t");
            }
        }
    }//GEN-LAST:event_btReadMaskActionPerformed

    private void readMask() {
        String str = "";
        txtMask.setText(txtMask.getText().trim());
        mask = new double[txtMask.getLineCount()][];
        try {
            BufferedReader in = new BufferedReader(new StringReader(txtMask.getText()));
            int y = 0;
            while ((str = in.readLine()) != null) {
                String[] elem = str.split(" ");
                mask[y] = new double[elem.length];
                for (int x = 0; x < elem.length; x++) {
                    mask[y][x] = Double.parseDouble(elem[x]);
                }
                y++;
            }
            k_mask = new float[mask.length * mask[0].length];
            for (int yy = 0; yy < mask.length; yy++) {
                for (int xx = 0; xx < mask[yy].length; xx++) {
                    k_mask[yy * mask[yy].length + xx] = (int) mask[yy][xx];
                }
            }
        } catch (Exception e) {
        }
    }

    private void setMask() {
        readMask();
        if (cbGrey.isSelected()) {
            BufferedImage buff = new BufferedImage(imagemOriginal.getWidth(), imagemOriginal.getHeight(), imagemOriginal.getType());
            Kernel kernel = new Kernel(mask.length, mask[0].length, k_mask);
            ConvolveOp op = new ConvolveOp(kernel);
            op.filter(imagemOriginal, buff);
            imagemPanel = buff;
            insertImage(deepCopy(buff), pImagem);
        } else {
            //converte a imagem para preto e branco
            BufferedImage image = new BufferedImage(imagemOriginal.getWidth(), imagemOriginal.getHeight(), BufferedImage.TYPE_BYTE_GRAY);
            Graphics g = image.getGraphics();
            g.drawImage(imagemOriginal, 0, 0, imagemOriginal.getWidth(), imagemOriginal.getHeight(), null);
            g.dispose();

            BufferedImage buff = new BufferedImage(image.getWidth(), image.getHeight(), image.getType());
            Kernel kernel = new Kernel(mask.length, mask[0].length, k_mask);
            ConvolveOp op = new ConvolveOp(kernel);
            op.filter(image, buff);
            imagemPanel = buff;
            insertImage(deepCopy(buff), pImagem);
        }
    }

    private void applyMask(BufferedImage bi, BufferedImage bi2, int py, int px) {
        readMask();
        int cx = mask[0].length / 2;
        int cy = mask.length / 2;
        //  System.out.print("\n PIXEL " + px + " : " + py + " : ");
        int sum = 0;



        int[] colorsf = new int[3];
        for (int i = 0; i < 1; i++) {
            for (int y = -cy; y <= cy; y++) {
                for (int x = -cx; x <= cx; x++) {

                    //garantir que o pixel existe
                    if (px + x < bi.getWidth() && px + x >= 0 && py + y < bi.getHeight() && py + y >= 0) {
                        int pixel = bi.getRGB(px + x, py + y);
                        int[] colors = {0xff & (pixel >> 16), 0xff & (pixel >> 8), 0xff & (pixel)};

                        //  System.out.print(" ("+(y+py) + " " + (x+px)+")");

                        colorsf[i] += colors[i] * mask[y + cy][x + cx];
                        if (colorsf[i] <= 0) {
                            colorsf[i] = 0;
                        } else if (colorsf[i] >= 255) {
                            colorsf[i] = 255;
                        }
                    }
                }
            }
        }

        //int r = 0xff & (sum >> 16);
        //int g = 0xff & (sum >> 8);
        //int b = 0xff & (sum);
        //System.out.println(colorsf[0]);
        //colocar na edge
        bi2.setRGB(px, py, ((colorsf[0] << 16) | (colorsf[0] << 8) | colorsf[0]));
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        BufferedImage imagemDestino = deepCopy(imagemOriginal);
//        try {
//            for (int i = 0; i < imagemOriginal.getHeight(); i++) {
//                for (int j = 0; j < imagemOriginal.getWidth(); j++) {
//                    applyMask(imagemOriginal, imagemDestino, i, j);
//                }
//            }
//            ImageIO.write(imagemDestino, "JPG", new File("edgeteste.jpg"));
//            // insertImage(imagemOriginal, pImagem);
//        } catch (Exception ex) {
//            Logger.getLogger(index.class.getName()).log(Level.SEVERE, null, ex);
//        }
        //setMask();
        try {
            readMask();
            BufferedImage imagemDestino;
            FilterEdge detector = new FilterEdge(imagemOriginal, mask);
            detector.start();
            imagemDestino = detector.getEdgeImg();
            ImageIO.write(imagemDestino, "JPG", new File("egde1111111111111111111111111111.jpg"));
        } catch (IOException ex) {
        }





    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbOptionsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbOptionsItemStateChanged
        int Selection;
        Selection = cbOptions.getSelectedIndex();
        if (Selection == 0) {
            txtMask.setText("1 0 -1\n" + "2 0 -2\n" + "1 0 -1");
        } else if (Selection == 1) {
            txtMask.setText("1 1 1\n" + "1 2 1\n" + "1 1 1");
        } else if (Selection == 2) {
            txtMask.setText("-1 -1 -1\n" + "-1 9 -1\n" + "-1 -1 -1");
        } else if (Selection == 3) {
            txtMask.setText("0 0 -2\n" + "0 2 0\n" + "1 0 0");
        } else if (Selection == 4) {
            txtMask.setText("0 0 1\n" + "0 0 0\n" + "1 0 0");
        } else if (Selection == 5) {
            txtMask.setText("-1 -1 -1\n" + "-1 8 -1\n" + "-1 -1 -1");
        }
    }//GEN-LAST:event_cbOptionsItemStateChanged

    private void pImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pImagemMouseClicked
        btLoadImg.doClick();
    }//GEN-LAST:event_pImagemMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        readMask();
        BufferedImage buff = new BufferedImage(imagemPanel.getWidth(), imagemPanel.getHeight(), imagemPanel.getType());
        Kernel kernel = new Kernel(3, 3, k_mask);
        ConvolveOp op = new ConvolveOp(kernel);
        op.filter(imagemPanel, buff);
        insertImage(buff, pImagem);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new index().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCanny;
    private javax.swing.JButton btCombine;
    private javax.swing.JButton btLoadImg;
    private javax.swing.JButton btPrewitt;
    private javax.swing.JToggleButton btReadMask;
    private javax.swing.JButton btRoberts;
    private javax.swing.JButton btSaveImg;
    private javax.swing.JButton btSobel;
    private javax.swing.JCheckBox cbGrey;
    private javax.swing.JComboBox cbOptions;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pImagem;
    private javax.swing.JTextArea txtMask;
    // End of variables declaration//GEN-END:variables
}
